server:
  port: 8081

spring:
  application:
    name: HelpdeskApp
  profiles:
    active: dev
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  hikari:
    maximum-pool-size: 10     # max number of connections in pool
    minimum-idle: 5           # min idle connections
    idle-timeout: 30000       # 30s before idle connection is removed
    max-lifetime: 1800000     # 30 mins, max lifetime of a connection
    connection-timeout: 20000 # 20s timeout for getting a connection
  cache:
    type: redis
    data:
      redis:
        host: localhost
        port: 6379
#  jpa:
#    properties:
#      hibernate:
#        cache:
#          use_second_level_cache: true
#          use_query_cache: true
#          region:
#            factory_class: com.orange.redis.hibernate4.RedisRegionFactory
debug: false
